const actionTypes = {
  APP_LOAD: "APP_LOAD",
  REDIRECT: "REDIRECT",
  ARTICLE_SUBMITTED: "ARTICLE_SUBMITTED",
  PROFILE_PAGE_LOADED: "PROFILE_PAGE_LOADED",
  PROFILE_FAVORITES_PAGE_LOADED: "PROFILE_FAVORITES_PAGE_LOADED",
  PROFILE_PAGE_UNLOADED: "PROFILE_PAGE_UNLOADED",
  PROFILE_FAVORITES_PAGE_UNLOADED: "PROFILE_FAVORITES_PAGE_UNLOADED",
  HOME_PAGE_LOADED: "HOME_PAGE_LOADED",
  HOME_PAGE_UNLOADED: "HOME_PAGE_UNLOADED",
  ASYNC_START: "ASYNC_START"
};

export default actionTypes;
