const actionTypes = {
  EDITOR_PAGE_LOADED: "EDITOR_PAGE_LOADED",
  EDITOR_PAGE_UNLOADED: "EDITOR_PAGE_UNLOADED",
  UPDATE_FIELD_EDITOR: "UPDATE_FIELD_EDITOR",
  ADD_TAG: "ADD_TAG",
  REMOVE_TAG: "REMOVE_TAG"
};

export default actionTypes;
