const ArticleListActionTypes = {
  APPLY_TAG_FILTER: "APPLY_TAG_FILTER",
  SET_PAGE: "SET_PAGE",
  CHANGE_TAB: "CHANGE_TAB",
  ARTICLE_FAVORITED: "ARTICLE_FAVORITED",
  ARTICLE_UNFAVORITED: "ARTICLE_UNFAVORITED"
};

export default ArticleListActionTypes;
